version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: uy_home_finder
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge