spring:
  application:
    name: uy-home-finder
  datasource:
    url: jdbc:postgresql://localhost:5432/uy_home_finder
    username: postgres
    password: changeme
  jooq:
    sql-dialect: postgres
logging:
  level:
    org.javamoney: OFF
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%25.25t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%mdc){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
decorator:
  datasource:
    datasource-proxy:
      query:
        enable-logging: true
        log-level: info
        logger-name: SQL-QUERY
app:
  skrapers:
    gallito:
      url-template: "https://www.gallito.com.uy/inmuebles/casas/alquiler/pre-{minPrice}-{maxPrice}-dolares/sup-{minSquareMeter}-500-metros!cant={pageSize}"
      url-params:
        minPrice: 400
        maxPrice: 1000
        pageSize: 80
        minSquareMeter: 75
    infocasas:
      url-template: "https://www.infocasas.com.uy/alquiler/casas/desde-{minPrice}/hasta-{maxPrice}/dolares/m2-desde-{minSquareMeter}/edificados"
      url-params:
        minPrice: 400
        maxPrice: 1000
        minSquareMeter: 75
    mercadolibre:
      url-template: "https://listado.mercadolibre.com.uy/inmuebles/casas/alquiler/_PriceRange_{minPrice}UYU-{maxPrice}UYU_TOTAL*AREA_{minSquareMeter}m²-*"
      url-params:
        minPrice: 18000
        maxPrice: 35000
        minSquareMeter: 75